<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGSNyZB5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGSNyZB5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGSNyZB5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGSNyZB5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGSNyZB5\App_KernelDevDebugContainer([
    'container.build_hash' => 'GSNyZB5',
    'container.build_id' => '58d81d4f',
    'container.build_time' => 1632294956,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGSNyZB5');
