<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'simulation_start' => [[], ['_controller' => 'App\\Controller\\MainController::ajaxAction'], [], [['text', '/simulation_start']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
