<?php

namespace Container6mfFMlq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oh99XTqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Oh99XTq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oh99XTq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'peticion' => ['privates', '.errored..service_locator.Oh99XTq.App\\Entity\\Peticion', NULL, 'Cannot autowire service ".service_locator.Oh99XTq": it references class "App\\Entity\\Peticion" but no such service exists.'],
        ], [
            'peticion' => 'App\\Entity\\Peticion',
        ]);
    }
}
