<?php

namespace Container6mfFMlq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeticionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Oh99XTq.App\Entity\Peticion' shared service.
     *
     * @return \App\Entity\Peticion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Oh99XTq": it references class "App\\Entity\\Peticion" but no such service exists.');
    }
}
