<?php

namespace Container6mfFMlq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeticionTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PeticionType' shared autowired service.
     *
     * @return \App\Form\PeticionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PeticionType.php';

        return $container->privates['App\\Form\\PeticionType'] = new \App\Form\PeticionType();
    }
}
